### PR TITLE
add ActivateGroup, DestroyGroup, DestroyUnit

### PR DESCRIPTION
**Pull request by soerenmeier**
- `Group::activate({ group_name })`
- `Group::destroy({ group_name })`
- `Unit::destroy({ name })`

### CODE REVIEW

**Comment by soerenmeier** [comment]
The errors seem not related to this pr, probably caused by the new rust version.

**Comment by rkusa** [comment]
> The errors seem not related to this pr, probably caused by the new rust version.

Fixed them on `main`, you might have to rebase. Sorry for that.

**Comment by soerenmeier** [comment]
Done

**Review by rkusa — APPROVED** [review]
Thanks, well done 👍

**Pull request merged**
