### PR TITLE
Update to new .getCategory

### PR DESCRIPTION
**Pull request by Penecruz**
Update the code to be compatible with the new `.getCategory()` implementation which ED changed in the latest release.

### CODE REVIEW

**Comment by peterb154** [comment]
Note comment in issue https://github.com/DCS-gRPC/rust-server/issues/246#issuecomment-1817895704

**Comment by martinco** [comment]
I've also been running with the same set of changes as this PR, with the additional change to the reference in `lua/DCS-gRPC/methods/controllers.lua` updated.

I haven't had any issues since, no errors, or stream stopping (I left only the `group:getCategory()` in `exporters/object.lua` for group as i haven't had a chance to test it but with 900 units, and regular destruction and player slot changes on a multiplayer server, no issues since making this set of changes

**Comment by mobot-gh** [comment]
> I haven't had any issues since, no errors, or stream stopping (I left only the `group:getCategory()` in `exporters/object.lua` for group as i haven't had a chance to test it but with 900 units, and regular destruction and player slot changes on a multiplayer server, no issues since making this set of changes

If the reference in `exporters/object.lua` is left as is, the return values will be from the `Group.Category` enum and not the `Object.Category` enum, right? If so, any client code with conditionals based on that value would need to be tweaked unless the line is changed, like the others, to `Object.getCategory(group)`.

**Comment by martinco** [comment]
Sorry for the confusion, all I meant by that anecdote was more the other unit known case and that seems good

But in the group case I haven't checked the behavior/ what it should be and would be guesswork on my part to change without verification/cause  so pointed it out but haven't acted on it 

Apologies for the anecdote; its more that it's not impacting me doesn't mean it's not a problem

**Comment by mobot-gh** [comment]
> Sorry for the confusion, all I meant by that anecdote was more the other unit known case and that seems good
> 
> But in the group case I haven't checked the behavior/ what it should be and would be guesswork on my part to change without verification/cause so pointed it out but haven't acted on it
> 
> Apologies for the anecdote; its more that it's not impacting me doesn't mean it's not a problem

No need to apologise, I added my comment as more of a question to see if it is only units that are affected by the change to `.getCategory()` or if Weapons, Groups, and Statics are also included. Maybe `mygroup:getCategory()` was already returning values from the `Group.Category` enum? Only some more testing will help us understand unless someone knows for certain already.

**Comment by Penecruz** [comment]
Uncertain of other impacts, the changes in this PR have allowed OverlordBot to function without issue, which is my only application using DCS-gRPC. My understanding was only Object was returning incorrect data prior to the change ED made in latest OB.

**Comment by rurounijones** [comment]
Can you rebase this on to the current main branch which should fix lint failures.

**Comment by mobot-gh** [comment]
There is also the reference mentioned by @martinco on [L25 of controllers.lua](https://github.com/DCS-gRPC/rust-server/blob/db29d0248396a25fcfd26cbcce379052db96f11a/lua/DCS-gRPC/methods/controllers.lua#L25)? Should that be included in this PR?

**Comment by Penecruz** [comment]
> There is also the reference mentioned by @martinco on [L25 of controllers.lua](https://github.com/DCS-gRPC/rust-server/blob/db29d0248396a25fcfd26cbcce379052db96f11a/lua/DCS-gRPC/methods/controllers.lua#L25). Should that be included in this PR?

Not needed in this case.

**Review by rurounijones — APPROVED** [review]

**Pull request merged**
