### PR TITLE
Added MetadataService with GetHealth and GetVersion

### PR DESCRIPTION
**Pull request by dutchie032**
Added an additional service. "AdministrationService" for admin functionality that does not touch DCS itself. 

`GetHealth`  => for getting the gRPC server status 
`GetVersion` => for getting the version of the cargo package. 

Nothing too fancy, but can be handy for the client and verification.

Example requests: 

image
image

### CODE REVIEW

**Comment by dutchie032** [comment]
Apologies for the manier protolint fix commits haha

**Review by rurounijones — COMMENTED** [review]
Can we rename `AdministrationtService` to `MetadataService` or something that is VERY unlikely to ever have a name clash.

`Administration` is such a generic term that I could see it being useful in other contexts.

**Comment by dutchie032** [comment]
Update the name to `MetadataService`. Chose `AdministrationService` due to it's administrative nature, but can imagine that indeed in the future there might be more "Administrator" type of services, so `Metadata` works for me

**Comment by rurounijones** [comment]
@dutchie032 Branch needs rebasing with merge conflicts, PR and README still says `AdministrationService`

**Comment by dutchie032** [comment]
@rurounijones conflicts resolved and namings fixed

**Review by rurounijones — APPROVED** [review]

**Pull request merged**
