### PR TITLE
CI: Lint Check of proto files

### PR DESCRIPTION
**Pull request by justin-lovell**
During the CI build, ensure that the files meet the styleguide.

Some of the errors were resolved in other PR's created.

### CODE REVIEW

**Comment by justin-lovell** [comment]
Well, it works.
image

**Comment by rurounijones** [comment]
I am not in favour of doing this _yet_. It forces decisions that do not need to be made yet while we still figure things out (the linked stuff about enums, waypoints etc. etc. being a good example).

**Comment by justin-lovell** [comment]
> not need to be forced early just to satisfy a linter

Almost every PR has a mention on how the `protobuf` definitions are not meeting the styleguide, which is what the linter is supposed to enforce.

More importantly -- most of the specific items which the linter is complaining about does not have an implementation / behavior. It should be encouraged that implementation should be followed up on those API's because it has demonstrated that it is expensive to think about whilst it doesn't have an influence on behavior.

**Comment by justin-lovell** [comment]
PR is ready for review.

**Review by rurounijones — APPROVED** [review]

**Pull request merged**
